import gg.meza.stonecraft.mod
import org.gradle.api.tasks.bundling.AbstractArchiveTask
import org.gradle.language.jvm.tasks.ProcessResources

plugins {
    id("gg.meza.stonecraft")
}

repositories {
    maven("https://maven.terraformersmc.com/") { name = "TerraformersMC" } // Mod Menu
    maven("https://maven.shedaniel.me/") { name = "Shedaniel" } // Cloth Config
}

// Mojmap-only targets (no yarn_mappings key, e.g. 26.2+) have nothing to remap -
// Minecraft ships already-deobfuscated - so Loom doesn't create the remap-aware "mod*"
// configuration family there (modImplementation, modCompileOnly, modLocalRuntime, ...),
// only plain implementation/compileOnly/localRuntime. Separately, cloth-config-fabric's
// currently-published 26.2 build still ships an access-widener file targeting the
// "intermediary" namespace (meant for the old remap pipeline), which Loom rejects
// outright on a no-remap target ("Expected official namespace for access widener entry,
// found: intermediary") - a real, current ecosystem-maturity gap in Cloth Config's own
// 26.2 build, not something fixable from this project. Until that's fixed upstream,
// Cloth Config (and therefore the config screen it powers) is skipped entirely on
// Mojmap-only targets - see the migration plan doc's Progress section for when this was
// last checked.
val hasYarnMappings = project.hasProperty("yarn_mappings")
val hasConfigScreenSupport = hasYarnMappings

// Cloth Config genuinely publishes Fabric, Forge, *and* NeoForge builds - but this mod's
// own config-screen integration only actually exists on Fabric (ModMenuIntegration.java).
// Wiring the equivalent for Forge/NeoForge (Forge's ConfigScreenHandler /
// IConfigScreenFactory, both straightforward to register) was attempted, but Cloth
// Config's Forge/NeoForge artifacts are ordinary third-party Maven jars compiled against
// real Mojang mappings, never remapped by Architectury Loom the way modImplementation
// remaps Fabric dependencies (Loom only remaps the vanilla/loader jars it manages
// itself) - confirmed via javap against the real cloth-config-forge/-neoforge jars and
// against this project's actual compile classpath (neither exposes the other's class
// names at all, so there's no cast/qualification that bridges them, and Architectury
// Loom's own docs confirm this interoperability gap isn't currently addressed by the
// plugin). Revisit if Cloth Config ever ships Yarn-mapped Forge/NeoForge builds, or if
// Loom adds a remapping mechanism for this case.
dependencies {
    if (hasConfigScreenSupport && mod.isFabric) {
        "modImplementation"("me.shedaniel.cloth:cloth-config-fabric:${project.property("cloth_config_version")}")

        // Mod Menu is an optional/soft dependency: the mod works completely fine
        // without it installed. modCompileOnly + modLocalRuntime lets us compile
        // against and test the ModMenu integration in the dev environment
        // (./gradlew runClient) without forcing every player to install Mod Menu.
        "modCompileOnly"("com.terraformersmc:modmenu:${project.property("modmenu_version")}")
        "modLocalRuntime"("com.terraformersmc:modmenu:${project.property("modmenu_version")}")
    }
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the
    // "build" task if it is present. If you remove this, sources will not be generated.
    withSourcesJar()
}

modSettings {
    // Default is per-chiseled-subproject (versions/<target>/src/main/generated), which
    // would silently split datagen output away from the single, version-controlled
    // src/main/generated tree every other loader/version target also needs to read.
    //
    // Split in two by mapping set, not shared unconditionally: worldgen registry JSON
    // (configured_feature/placed_feature) is genuinely schema-incompatible between Yarn
    // targets (<26.2, e.g. Feature.FLOWER/RandomPatchFeatureConfig) and Mojmap-only
    // targets (>=26.2, e.g. Feature.SIMPLE_BLOCK/SimpleBlockConfiguration - see
    // ModConfiguredFeatures/ModPlacedFeatures) - confirmed via a real 26.2-fabric crash
    // ("Unknown registry key ... minecraft:flower") from shipping the Yarn-schema JSON
    // unchanged to a Mojmap target. Each directory is regenerated by running datagen
    // (chiseledDatagen, or runDatagen on a single chiseled target) from a target on the
    // matching side of this split, and both are checked in.
    generatedResources = rootProject.layout.projectDirectory.dir(
        if (hasYarnMappings) "src/main/generated" else "src/main/generated-mojmap"
    )
}

// Recipe/advancement JSON is also datagen'd (ModRecipeProvider) rather than hand-
// maintained, but it can't share modSettings.generatedResources above: that's a 2-way
// split (Yarn/Mojmap) matching worldgen's own schema boundary, while Mojang's recipe
// format actually changed on a *different* boundary (1.20.1 / 1.21-1.21.10 / 1.21.11+ -
// confirmed by decompiling the real game's ItemStack/Ingredient codecs and RegistryKeys.
// RECIPE's registry path for each version - see ModRecipeProvider's own doc comment).
// It also can't just reuse runDatagen's single shared output root for more than one of
// these groups at once even if a directory were shared: Fabric's own recipe-provider
// cache identity ("Recipes", from vanilla RecipeProvider.getName(), which is final and
// can't be overridden to disambiguate) is fixed regardless of which format a given
// Stonecutter branch is emitting, so a *second* group's regen run into the same
// directory would see the first group's files as stale and delete them - confirmed by
// inspecting the real per-provider cache manifest Fabric writes under generated/.cache/,
// not assumed. Each group therefore gets its own permanently-separate, hand-named
// directory, regenerated by running :<version>-fabric:runDatagen and relocating that
// run's data/emeraldisleflora/{recipes,advancements} output out of whichever directory
// modSettings.generatedResources pointed at for that target, into the directory below -
// see CONTRIBUTING.md for the exact steps. null means "not generated yet for this
// version" (see ModRecipeProvider's own <1.21.11 gating) - only 1.20.1 exists so far.
val recipeGeneratedResources: String? = when {
    mod.minecraftVersion == "1.20.1" -> "src/main/generated-recipes-1.20.1"
    else -> null
}

// fabric.mod.json hard-depends on cloth-config, but Mojmap-only targets skip Cloth
// Config entirely (see the dependencies{} block above) - a real, un-emptied "depends"
// entry there would make Fabric Loader flatly refuse to load the mod on a clean 26.2+
// install (confirmed: this is exactly what blocked running datagen on 26.2-fabric with
// no cloth-config jar already present). fabric.mod.json has no Stonecutter comment
// processing of its own (unlike the .java sources), so this uses the same
// ${...}-token/expand() templating already used there for ${version}/${minecraftVersion}
// - the token expands to a full ",\n\t\t\"cloth-config\": \"*\"" line (kept out of
// "depends" entirely, not just emptied, so the JSON stays valid either way) only when
// yarn_mappings is present.
val clothConfigDependsLine = if (hasYarnMappings) ",\n\t\t\"cloth-config\": \"*\"" else ""
tasks.named<ProcessResources>("processResources") {
    // A plain content filter, not expand() - Stonecraft's own processResources config
    // already calls expand() for ${version}/${minecraftVersion}/etc. on this same file,
    // and a second expand() call (Groovy SimpleTemplateEngine-based) clobbers that
    // existing filter chain instead of composing with it ("Missing property (version)").
    // filter{} closures chain safely regardless of order, so this uses its own distinct
    // (non-${...}) placeholder token to stay out of the templating engine's way entirely.
    filesMatching("fabric.mod.json") {
        filter { line -> line.replace("@CLOTH_CONFIG_DEPENDS_LINE@", clothConfigDependsLine) }
    }
}

// Stonecraft only auto-adds generatedResources to the resources source set for
// ForgeLike targets (see Java.kt); Fabric needs it added explicitly or datagen output
// silently drops out of the built jar. Doing this unconditionally for ForgeLike too
// double-registers the same srcDir and breaks sourcesJar with a duplicate-entry error.
if (mod.isFabric) {
    sourceSets.main {
        resources.srcDir(modSettings.generatedResources)
    }
}

// recipeGeneratedResources isn't covered by Stonecraft's own ForgeLike auto-add (that
// only applies to modSettings.generatedResources itself), so every loader needs it added
// explicitly here - unlike the block above, there's no Fabric/ForgeLike split to worry
// about double-registering, since this is a plain project directory, not something
// Stonecraft already wires in for one loader family.
if (recipeGeneratedResources != null) {
    sourceSets.main {
        resources.srcDir(rootProject.layout.projectDirectory.dir(recipeGeneratedResources))
    }
}

tasks.named<Jar>("jar") {
    from(rootProject.layout.projectDirectory.file("LICENSE")) {
        rename { "${it}_${mod.id}" }
    }
}

// Dev convenience: copy this target's built jar into the matching Prism Launcher
// instance's mods folder, for real-install testing outside Loom's dev-launch
// environment (which has known bugs, unrelated to this mod, on some targets - see the
// migration plan doc under .agents/plans/). Instance folder names are expected to match
// the chiseled subproject name exactly (e.g. "1.21.11-neoforge"). Override
// prismInstancesDir (gradle.properties or -PprismInstancesDir=...) if your Prism data
// directory differs; targets without a matching instance are skipped, not failed, so
// this stays safe to run across the whole matrix at once.
val prismInstancesDir = (project.findProperty("prismInstancesDir") as String?)
    ?: "/home/Rhonan/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances"

tasks.register<Copy>("deployToPrism") {
    group = "deployment"
    description = "Copies the built jar into this target's matching Prism Launcher instance's mods folder."

    val instanceDir = file(prismInstancesDir).resolve(project.name)
    val modsDir = instanceDir.resolve("minecraft/mods")
    // Mojmap-only targets (no yarn_mappings, e.g. 26.2+) have nothing to remap, so Loom
    // doesn't create a remapJar task there - fall back to the plain jar task's output.
    val jarTaskName = if (tasks.names.contains("remapJar")) "remapJar" else "jar"
    val jarTask = tasks.named<AbstractArchiveTask>(jarTaskName)
    dependsOn(jarTask)

    onlyIf {
        val exists = instanceDir.exists()
        if (!exists) logger.warn("deployToPrism: no Prism instance '${project.name}' at $instanceDir, skipping")
        exists
    }

    doFirst {
        modsDir.mkdirs()
        modsDir.listFiles { f -> f.name.startsWith("${mod.id}-") && f.name.endsWith(".jar") }
            ?.forEach { it.delete() }
    }

    from(jarTask.flatMap { it.archiveFile })
    into(modsDir)
}

// Stonecraft's own configurePublishing() (applied automatically per chiseled
// subproject, before this block runs - see its real source,
// gg/meza/stonecraft/configurations/Publishing.kt, decompiled from the pinned 1.12.5
// jar to confirm rather than guessed) already wires up File/modLoaders/minecraftVersions/
// credentials/dryRun correctly for every target with zero code here. This block only
// overrides the three things worth a project-specific choice:
// - version/displayName: Stonecraft's own defaults ("${mod.version}+${mod.loader}-
//   $minecraftVersion" / "${mod.version} for ${loader} $minecraftVersion") are reasonable
//   but don't include the mod name and order loader/version the other way round - matches
//   what was actually decided on, not just accepting the framework default silently.
// - changelog: Stonecraft's own default publishes the *entire* CHANGELOG.md verbatim to
//   every single version on every platform - fine for a single-version mod, but with 8
//   targets per release that means players see the whole project history repeated 8
//   times instead of just what's new in this release. Extracts just the section for the
//   current mod.version instead (Keep a Changelog format - see CHANGELOG.md itself).
val changelogForCurrentVersion = run {
    val file = rootProject.layout.projectDirectory.file("CHANGELOG.md").asFile
    if (!file.exists()) return@run "No changelog provided."
    val lines = file.readLines()
    val start = lines.indexOfFirst { it.startsWith("## [${mod.version}]") }
    if (start == -1) return@run "No changelog provided."
    val end = lines.drop(start + 1).indexOfFirst { it.startsWith("## ") }
        .let { if (it == -1) lines.size else start + 1 + it }
    lines.subList(start + 1, end).joinToString("\n").trim()
}

// mod.loader is the lowercase Stonecutter loader id ("fabric"/"forge"/"neoforge") -
// replaceFirstChar{} alone would render NeoForge as "Neoforge", so this maps the one
// case that actually needs it explicitly rather than guessing at a capitalization rule.
val loaderDisplayName = when (mod.loader) {
    "neoforge" -> "NeoForge"
    else -> mod.loader.replaceFirstChar { it.uppercase() }
}

publishMods {
    version.set("${mod.version}+${mod.minecraftVersion}-${mod.loader}")
    displayName.set("${mod.name} ${mod.version} ($loaderDisplayName ${mod.minecraftVersion})")
    changelog.set(changelogForCurrentVersion)

    // Gated the same way Stonecraft's own configurePublishing() gates its Modrinth
    // block: calling modrinth{} unconditionally creates the publishModrinth task
    // regardless of whether Stonecraft's own auto-config actually ran (it skips
    // entirely, with just a log line, when MODRINTH_TOKEN/MODRINTH_ID aren't set) -
    // confirmed the hard way, this fails validation locally with "projectId doesn't
    // have a configured value" otherwise, since project id/token are only ever set by
    // Stonecraft's own block, never by this one.
    if (project.providers.environmentVariable("MODRINTH_TOKEN").isPresent &&
        project.providers.environmentVariable("MODRINTH_ID").isPresent) {
        modrinth {
            // Matches this mod's real dependencies{} block above and fabric.mod.json
            // (see clothConfigDependsLine for why cloth-config is conditional there) -
            // Fabric API is required on every Fabric target. Cloth Config is itself a
            // real multi-loader mod (Fabric, Forge, *and* NeoForge all publish it), but
            // that's not what this declares: it declares what *this mod* actually
            // depends on, which is Cloth Config + Mod Menu on Fabric only - this mod has
            // no Forge/NeoForge config-screen integration (see the dependencies{} block
            // comment above for why that isn't currently feasible), so claiming either
            // dependency there would describe an integration that doesn't exist.
            if (mod.isFabric) {
                requires("fabric-api")
                if (hasConfigScreenSupport) {
                    requires("cloth-config")
                    optional("modmenu")
                }
            }
        }
    }
}
