import gg.meza.stonecraft.mod
import org.gradle.api.tasks.bundling.AbstractArchiveTask
import org.gradle.language.jvm.tasks.ProcessResources

plugins {
    id("gg.meza.stonecraft")
}

repositories {
    maven("https://maven.terraformersmc.com/") { name = "TerraformersMC" } // Mod Menu
    maven("https://maven.shedaniel.me/") { name = "Shedaniel" } // Cloth Config
}

// Mojmap-only targets (no yarn_mappings key, e.g. 26.2+) have nothing to remap -
// Minecraft ships already-deobfuscated - so Loom doesn't create the remap-aware "mod*"
// configuration family there (modImplementation, modCompileOnly, modLocalRuntime, ...),
// only plain implementation/compileOnly/localRuntime. Separately, cloth-config-fabric's
// currently-published 26.2 build still ships an access-widener file targeting the
// "intermediary" namespace (meant for the old remap pipeline), which Loom rejects
// outright on a no-remap target ("Expected official namespace for access widener entry,
// found: intermediary") - a real, current ecosystem-maturity gap in Cloth Config's own
// 26.2 build, not something fixable from this project. Until that's fixed upstream,
// Cloth Config (and therefore the Mod Menu integration that surfaces its screen) is
// skipped entirely on Mojmap-only targets - same accepted-gap treatment this project
// already gives the config GUI on Forge/NeoForge (see the migration plan doc).
val hasYarnMappings = project.hasProperty("yarn_mappings")
val hasConfigScreenSupport = hasYarnMappings

dependencies {
    if (mod.isFabric && hasConfigScreenSupport) {
        // Cloth Config powers our in-game config screen. It's a real dependency (not
        // optional) since it's what the sample config option's GUI is built from.
        "modImplementation"("me.shedaniel.cloth:cloth-config-fabric:${project.property("cloth_config_version")}")

        // Mod Menu is an optional/soft dependency: the mod works completely fine
        // without it installed. modCompileOnly + modLocalRuntime lets us compile
        // against and test the ModMenu integration in the dev environment
        // (./gradlew runClient) without forcing every player to install Mod Menu.
        "modCompileOnly"("com.terraformersmc:modmenu:${project.property("modmenu_version")}")
        "modLocalRuntime"("com.terraformersmc:modmenu:${project.property("modmenu_version")}")
    }
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the
    // "build" task if it is present. If you remove this, sources will not be generated.
    withSourcesJar()
}

modSettings {
    // Default is per-chiseled-subproject (versions/<target>/src/main/generated), which
    // would silently split datagen output away from the single, version-controlled
    // src/main/generated tree every other loader/version target also needs to read.
    //
    // Split in two by mapping set, not shared unconditionally: worldgen registry JSON
    // (configured_feature/placed_feature) is genuinely schema-incompatible between Yarn
    // targets (<26.2, e.g. Feature.FLOWER/RandomPatchFeatureConfig) and Mojmap-only
    // targets (>=26.2, e.g. Feature.SIMPLE_BLOCK/SimpleBlockConfiguration - see
    // ModConfiguredFeatures/ModPlacedFeatures) - confirmed via a real 26.2-fabric crash
    // ("Unknown registry key ... minecraft:flower") from shipping the Yarn-schema JSON
    // unchanged to a Mojmap target. Each directory is regenerated by running datagen
    // (chiseledDatagen, or runDatagen on a single chiseled target) from a target on the
    // matching side of this split, and both are checked in.
    generatedResources = rootProject.layout.projectDirectory.dir(
        if (hasYarnMappings) "src/main/generated" else "src/main/generated-mojmap"
    )
}

// fabric.mod.json hard-depends on cloth-config, but Mojmap-only targets skip Cloth
// Config entirely (see the dependencies{} block above) - a real, un-emptied "depends"
// entry there would make Fabric Loader flatly refuse to load the mod on a clean 26.2+
// install (confirmed: this is exactly what blocked running datagen on 26.2-fabric with
// no cloth-config jar already present). fabric.mod.json has no Stonecutter comment
// processing of its own (unlike the .java sources), so this uses the same
// ${...}-token/expand() templating already used there for ${version}/${minecraftVersion}
// - the token expands to a full ",\n\t\t\"cloth-config\": \"*\"" line (kept out of
// "depends" entirely, not just emptied, so the JSON stays valid either way) only when
// yarn_mappings is present.
val clothConfigDependsLine = if (hasYarnMappings) ",\n\t\t\"cloth-config\": \"*\"" else ""
tasks.named<ProcessResources>("processResources") {
    // A plain content filter, not expand() - Stonecraft's own processResources config
    // already calls expand() for ${version}/${minecraftVersion}/etc. on this same file,
    // and a second expand() call (Groovy SimpleTemplateEngine-based) clobbers that
    // existing filter chain instead of composing with it ("Missing property (version)").
    // filter{} closures chain safely regardless of order, so this uses its own distinct
    // (non-${...}) placeholder token to stay out of the templating engine's way entirely.
    filesMatching("fabric.mod.json") {
        filter { line -> line.replace("@CLOTH_CONFIG_DEPENDS_LINE@", clothConfigDependsLine) }
    }
}

// Stonecraft only auto-adds generatedResources to the resources source set for
// ForgeLike targets (see Java.kt); Fabric needs it added explicitly or datagen output
// silently drops out of the built jar. Doing this unconditionally for ForgeLike too
// double-registers the same srcDir and breaks sourcesJar with a duplicate-entry error.
if (mod.isFabric) {
    sourceSets.main {
        resources.srcDir(modSettings.generatedResources)
    }
}

tasks.named<Jar>("jar") {
    from(rootProject.layout.projectDirectory.file("LICENSE")) {
        rename { "${it}_${mod.id}" }
    }
}

// Dev convenience: copy this target's built jar into the matching Prism Launcher
// instance's mods folder, for real-install testing outside Loom's dev-launch
// environment (which has known bugs, unrelated to this mod, on some targets - see the
// migration plan doc under .agents/plans/). Instance folder names are expected to match
// the chiseled subproject name exactly (e.g. "1.21.11-neoforge"). Override
// prismInstancesDir (gradle.properties or -PprismInstancesDir=...) if your Prism data
// directory differs; targets without a matching instance are skipped, not failed, so
// this stays safe to run across the whole matrix at once.
val prismInstancesDir = (project.findProperty("prismInstancesDir") as String?)
    ?: "/home/Rhonan/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances"

tasks.register<Copy>("deployToPrism") {
    group = "deployment"
    description = "Copies the built jar into this target's matching Prism Launcher instance's mods folder."

    val instanceDir = file(prismInstancesDir).resolve(project.name)
    val modsDir = instanceDir.resolve("minecraft/mods")
    // Mojmap-only targets (no yarn_mappings, e.g. 26.2+) have nothing to remap, so Loom
    // doesn't create a remapJar task there - fall back to the plain jar task's output.
    val jarTaskName = if (tasks.names.contains("remapJar")) "remapJar" else "jar"
    val jarTask = tasks.named<AbstractArchiveTask>(jarTaskName)
    dependsOn(jarTask)

    onlyIf {
        val exists = instanceDir.exists()
        if (!exists) logger.warn("deployToPrism: no Prism instance '${project.name}' at $instanceDir, skipping")
        exists
    }

    doFirst {
        modsDir.mkdirs()
        modsDir.listFiles { f -> f.name.startsWith("${mod.id}-") && f.name.endsWith(".jar") }
            ?.forEach { it.delete() }
    }

    from(jarTask.flatMap { it.archiveFile })
    into(modsDir)
}
