name: build-pull-request

on:
  pull_request:
    branches: ["main"]
    paths-ignore: ["**.md"]

env:
  JAVA_VERSION: 21

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout The Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0

      - name: Initialize Caches
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v5.1.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-pr-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-pr-

      - name: Build mod
        uses: ./.github/actions/build-mod
        with:
          java-version: ${{ env.JAVA_VERSION }}